[package]
name = "lucid_lint"
version = "0.1.0"
authors = ["Samit Basu <samit.basu@smiths.com>"]
edition = "2018"

[dependencies]
clap = {version = "~2.32", features = ["yaml"]}
num-bigint = "0.2"
ndarray = "0.12.1"
num-traits = "0.2.6"
assert_cli = "0.6.3"